<?php declare( strict_types=1 );

namespace A8C\SpecialProjects\PluginTemplate\Integrations\WC_Subscriptions;

\defined( 'ABSPATH' ) || exit;

/**
 * Builds the demonstration note appended to subscription price strings; replace this with the
 * integration's real behavior.
 *
 * A plain collaborator: the feature's `Component` constructs it in `initialize()` and attaches
 * its callback in `register_hooks()`; it implements no plugin contract of its own.
 *
 * @since   1.0.0
 * @version 1.0.0
 */
final class Price_Note {
	// region HOOKS

	/**
	 * Appends the template's demonstration note to the companion-generated subscription price
	 * string.
	 *
	 * @since   1.0.0
	 * @version 1.0.0
	 *
	 * @param   string $price_string The price string WooCommerce Subscriptions generated.
	 *
	 * @return  string
	 */
	public function append( string $price_string ): string {
		return wp_sprintf(
			/* translators: %s: The subscription price string generated by WooCommerce Subscriptions */
			__( '%s (A8CSP Template Plugin example note)', 'a8csp-plugin-template' ),
			$price_string
		);
	}

	// endregion
}
